# ControlType, the type of target that needs to be detected
# None = 0,
# bluePerson = 1,
# RedPerson = 2,
# BlackCircle = 3,
# Car = 4,
# MedicalBag = 5,
# YellowPerson = 6,

int8 ControlType
---------------
bool setOk
