# goal definition
# The goal pose try to fly to
geometry_msgs/PoseStamped goal_pose
string fly_type
float32 fly_vel
---
# result definition
# the fianl Distance from the goal point
float32 final_distance
---
# feedback
# Distance from the goal point
float32 distance