// Generated by gencpp from file detect_track/ControlDetection.msg
// DO NOT EDIT!


#ifndef DETECT_TRACK_MESSAGE_CONTROLDETECTION_H
#define DETECT_TRACK_MESSAGE_CONTROLDETECTION_H

#include <ros/service_traits.h>


#include <detect_track/ControlDetectionRequest.h>
#include <detect_track/ControlDetectionResponse.h>


namespace detect_track
{

struct ControlDetection
{

typedef ControlDetectionRequest Request;
typedef ControlDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlDetection
} // namespace detect_track


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detect_track::ControlDetection > {
  static const char* value()
  {
    return "b418a6e2e6ff2264b54f7352bb0ed12b";
  }

  static const char* value(const ::detect_track::ControlDetection&) { return value(); }
};

template<>
struct DataType< ::detect_track::ControlDetection > {
  static const char* value()
  {
    return "detect_track/ControlDetection";
  }

  static const char* value(const ::detect_track::ControlDetection&) { return value(); }
};


// service_traits::MD5Sum< ::detect_track::ControlDetectionRequest> should match 
// service_traits::MD5Sum< ::detect_track::ControlDetection > 
template<>
struct MD5Sum< ::detect_track::ControlDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detect_track::ControlDetection >::value();
  }
  static const char* value(const ::detect_track::ControlDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_track::ControlDetectionRequest> should match 
// service_traits::DataType< ::detect_track::ControlDetection > 
template<>
struct DataType< ::detect_track::ControlDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::detect_track::ControlDetection >::value();
  }
  static const char* value(const ::detect_track::ControlDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detect_track::ControlDetectionResponse> should match 
// service_traits::MD5Sum< ::detect_track::ControlDetection > 
template<>
struct MD5Sum< ::detect_track::ControlDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detect_track::ControlDetection >::value();
  }
  static const char* value(const ::detect_track::ControlDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_track::ControlDetectionResponse> should match 
// service_traits::DataType< ::detect_track::ControlDetection > 
template<>
struct DataType< ::detect_track::ControlDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::detect_track::ControlDetection >::value();
  }
  static const char* value(const ::detect_track::ControlDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECT_TRACK_MESSAGE_CONTROLDETECTION_H
