// Generated by gencpp from file detect_track/ControlDetectionRequest.msg
// DO NOT EDIT!


#ifndef DETECT_TRACK_MESSAGE_CONTROLDETECTIONREQUEST_H
#define DETECT_TRACK_MESSAGE_CONTROLDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_track
{
template <class ContainerAllocator>
struct ControlDetectionRequest_
{
  typedef ControlDetectionRequest_<ContainerAllocator> Type;

  ControlDetectionRequest_()
    : ControlType(0)  {
    }
  ControlDetectionRequest_(const ContainerAllocator& _alloc)
    : ControlType(0)  {
  (void)_alloc;
    }



   typedef int8_t _ControlType_type;
  _ControlType_type ControlType;





  typedef boost::shared_ptr< ::detect_track::ControlDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_track::ControlDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlDetectionRequest_

typedef ::detect_track::ControlDetectionRequest_<std::allocator<void> > ControlDetectionRequest;

typedef boost::shared_ptr< ::detect_track::ControlDetectionRequest > ControlDetectionRequestPtr;
typedef boost::shared_ptr< ::detect_track::ControlDetectionRequest const> ControlDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_track::ControlDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_track

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_track::ControlDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_track::ControlDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_track::ControlDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "506f1fd1bdb2c9c02a91632248441f14";
  }

  static const char* value(const ::detect_track::ControlDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x506f1fd1bdb2c9c0ULL;
  static const uint64_t static_value2 = 0x2a91632248441f14ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_track/ControlDetectionRequest";
  }

  static const char* value(const ::detect_track::ControlDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ControlType\n\
";
  }

  static const char* value(const ::detect_track::ControlDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ControlType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_track::ControlDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_track::ControlDetectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "ControlType: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ControlType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_TRACK_MESSAGE_CONTROLDETECTIONREQUEST_H
