// Generated by gencpp from file detect_track/ControlDetectionResponse.msg
// DO NOT EDIT!


#ifndef DETECT_TRACK_MESSAGE_CONTROLDETECTIONRESPONSE_H
#define DETECT_TRACK_MESSAGE_CONTROLDETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_track
{
template <class ContainerAllocator>
struct ControlDetectionResponse_
{
  typedef ControlDetectionResponse_<ContainerAllocator> Type;

  ControlDetectionResponse_()
    : isOk(false)  {
    }
  ControlDetectionResponse_(const ContainerAllocator& _alloc)
    : isOk(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isOk_type;
  _isOk_type isOk;





  typedef boost::shared_ptr< ::detect_track::ControlDetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_track::ControlDetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlDetectionResponse_

typedef ::detect_track::ControlDetectionResponse_<std::allocator<void> > ControlDetectionResponse;

typedef boost::shared_ptr< ::detect_track::ControlDetectionResponse > ControlDetectionResponsePtr;
typedef boost::shared_ptr< ::detect_track::ControlDetectionResponse const> ControlDetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_track::ControlDetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_track

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_track::ControlDetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_track::ControlDetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_track::ControlDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba8951a653c7742f358b4db6e37fb3b";
  }

  static const char* value(const ::detect_track::ControlDetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba8951a653c7742ULL;
  static const uint64_t static_value2 = 0xf358b4db6e37fb3bULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_track/ControlDetectionResponse";
  }

  static const char* value(const ::detect_track::ControlDetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isOk\n\
\n\
";
  }

  static const char* value(const ::detect_track::ControlDetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isOk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlDetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_track::ControlDetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_track::ControlDetectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "isOk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isOk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_TRACK_MESSAGE_CONTROLDETECTIONRESPONSE_H
